### PR TITLE
Update to Rasa 3.9.1

### PR DESCRIPTION
**Pull request by tabergma**
## Description
- Update to Rasa 3.9.1
- New features:
  - [e2e test with metadata](https://github.com/RasaHQ/rasa-calm-demo/pull/36) 
  - [search](https://github.com/RasaHQ/rasa-calm-demo/pull/33) 
  - [slot improvements](https://github.com/RasaHQ/rasa-calm-demo/pull/30) and [slot management fixes](https://github.com/RasaHQ/rasa-calm-demo/pull/32)

## TODOs
[ ] compared flaky tests with the [known list of flaky tests steps](https://www.notion.so/rasa/Flaky-E2E-Test-Steps-63864d3d8c7b4427a0f3df8052e39f21)

### CODE REVIEW

**Review by ancalita — APPROVED** [review]
🎉

**Comment by tabergma** [comment]
@Northwind01 You added a section to the README "Running the project with enterprise search" but without any content. Do you want to add something there?

**Comment by tabergma** [comment]
Another question: Do we want to enable the search by default? I'm currently training with extractive search and it takes forever... 🤔

**Comment by tabergma** [comment]
Ok, I just double checked with a new virtual env and now everything works just fine. Also the additional section is not needed. Ready to merge 🚀

**Pull request merged**
